* 自我认识
每条分析自己最想做和最抗拒做的事情，并分析原因。


* 2025.10.09 周四 晴天
国庆节后回来的第一天，上午就是正常的上班，午饭的时候儿子开视频问我在干啥，有点惊讶。

最想做和最抗拒的事情真的很难说，主要是我很难说最，好像best就会确定了什么，不想下
一个最合适的决定。这样似乎自己就能"甩锅" 了一样；

今天最抗拒的事情是公司回来一个一直请假的员工。我一直觉得和长卫和赵坤很熟悉，就下意识的
认为中午要一直吃饭，心理面就一直担心。早上刚到工位就看到一堆糖果，就知道是喜糖，然后就
听到大家说是建军带回来的。我十分担心和他一起吃饭，好像自己要不如他了一样。但是事实也就是
如此，我是如此的担心自己和他的比较。上午和下午一直在评审需求我就感觉好了一点，觉得他又
不是很怎么样，好像不如我一样。
    为什么觉得他比我强，给我造成了威胁。首先是一直没有见到真人然后大家一直都在谈论他，
 就觉得大家很喜欢他，然后就觉得大家会讨厌我，不喜欢我。我就不如别人了。其次是听赵坤谈论
 他每两周就要回家一次，必须要回家看孩子。不用请假，每天晚上坐火车回去周一正常上班，执行能力很强
 这太顾家了，相比较我而言差别太大了，我觉得这是一个威胁，这是对我的一个指责。我不够对家庭认真负责。还有就是听到别人谈论他下班，一道五点
 半就走，好像也不用管别人，我觉得这是对我的威胁，他活的这么自然，真实，随心我就要考虑很多
 然后才能下班。再有一点就是我这边的代码审核要必要的审核人员就是他，我觉得自己要受他的检查
 好像怎么样是的，就是我不如他。
     我又从其他的地方找补，首先就是他在开会上的发言声音不是很有力，我觉得自己这点比他好。
 还有就是他找铃兰说话我看样貌觉得长相一般，心里面就平衡了许多。最后就是他最终还是没有和我们
 一起吃饭，这样我就少了许多和他面对面开始认识的压力，然后似乎他也不是这么受欢迎。

    最想做的事情不是今天，反而是前两天有一个冲动，游戏也不想打了，就是开发一个日志查询功能，可以
在搜索框直接输入文字，然后过滤出内容，有固定的关键词搜索，可以做成网页或者exe安装包，甚至问了chatGpt想要开始动手
想着自己把功能分享给大家，大家都在使用很开心，或者部署起来然后就让大家共同使用，我负责维护，这样自己就很有价值了。

    最终我也没有动手，脑中有重现了很多的困难，大家也不会在意于这个功能的，这太简陋了。只是把我原来公司做的软件
功能抄过来一样，有神么用呢，把文件从浏览器复制到本地进行搜索就行了，搞这么麻烦干嘛。反正大家都是这么使用的。

    今天其实也有一个冲动就是刷题，想要进步，但是没怎么做就过去了。如果我不去执行就慢慢的消失了这样的想法。

    上面是我今天花了二十多分钟的一个记录感觉还是挺好的，对我来说就像是写日记一样。
 


    
* 2025.10.10 周五 晴天

    看到了一个新闻，浙江那边的天气有39度。着实太高了，不可思议，已经是中秋了。
    今天很抗拒的一个事情就是起床，脑子里面在睡梦中想着自己的工作中的脚本修改，怎么和大家讲解，然后演示
的途中操作卡顿，让我很焦急；特别是必须起床的时候越来越想请一个假，那样自己就能好好的休息一下了，就像在
杭州那边一样，可是不行，最后我还是爬了起来，不知道为会有如此大的阻力，可能是自己不想面对自己有点棘手的
工作然后想逃避，害怕什么。但是上班的过程还是很和谐的，也很有精神，这边的工作似乎比在杭州还要舒服一点，这里
是在真正的工作，那边其余的杂事比较多，这里不会在你下班的时候要求你进行答疑什么的，这是最好的，不会让人没法
进行休息。而且要求个人提高技能，不管怎么样是一个双赢的局面。
    那么有没有很想做的事情，获取有就是想给媳妇开个视频，但是这个小小的冲动被压制下去了，最后不了了之。我时常
会有这样的冲动，但是最后都是被自己否定。或许觉得自己不够重要或许是觉得这是很小的一件事情，没有必要去这样做。
太多次了。
    不知道这样的练习会不会对我的写作造成什么真的提高，感觉就是自己一直以来的写作方式，似乎没有什么真的转变。我
还是幻想一种严肃文学一样，讲究结构，语法，修辞，文字的简介。想着自己在制作一件很好的很大的东西。工匠或者艺术家
一样。或许这种想法是真正对我造成大的伤害的想法，然后我不去练习就无法从小到大的成长，反正还有一个周总结，到时候
我会用纸来书写，但是那个时候不是周末有点难办，没事，周日写吧。
