* 完美主义
        我就有很深的影响，就是怕事情做不好，不知道怎么做，怕别人嘲笑你，最后只能
   拖着什么都不去做。

   知乎链接[[https://www.zhihu.com/question/667305227/answer/1989731197224493826][如何破除完美主义]]

   
* 摘要
#+begin_quote
=完美主义是认知上的缺陷，执行上的懒惰。=

如果我们选择了某一目标，但我们所具备的控制方法达不到所需要的控制能力又怎么办呢？
例如我们向月球发射一枚火箭，火箭要击中38万公里远的月球，这就好像在10公里外用步枪
瞄准一只苍蝇的眼睛一样困难。有人会以为火箭里一定装有一个非常精确的瞄准器，
发射之前一定按照算好的提前量对准月球发射的，就像步枪打飞鸟那样。其实这完全办不到。火箭在运动中要飞越38万公里的路程，有许多干扰根本无法事先估计到。发射前把轨道算得再精确，把发射方向控制得再准也不行。也就是说，仅仅依靠发射时控制方向是完全达不到这么大控制能力的。那么我们是不是就束手无策了呢？当然不是。我们有一些非常巧妙的方法来增强我们的控制能力。不过要解决这个问题还要先从“负反馈”这个概念谈起。
二次大战前后，随着科学技术的发展，飞机的速度越来越快，性能越来越好，
用老式高射炮来击落飞机也就越来越困难了。人们发现，无论怎样提高高射炮的准确性，
总是有限的。飞机飞行的轨道因驾驶员动作的随机性儿乎是不能预先求出的，经典的思想方法暴露出一些根本的缺点。
其实，这一类被工程师视为极困难的问题我们可以从自然界不少动物身上找到答案。
鹰击长空，不但能准确地扑到固定目标，甚至连飞速躲避的兔子、老鼠也不能逃脱。
显然，鹰没有也不可能事先计算自己和目标的运动方程。鹰不是按照事先计算好的路线飞行的。
鹰发现兔子后，马上用眼睛估计一下它和兔子的大致距离和相对位置，
然后选择一个大致的方向向兔子飞去。在这个过程中它的眼睛一直盯着兔子，
不断向大脑报告自己的位置跟兔子之间差距。不管兔子怎么跑，大脑作出的决定都是为了缩小自己跟兔子位置的差距。
这种决定通过翅膀来执行，随时改变着鹰的飞行方向和速度，调整鹰的位置，
使差距越来越小，直到这个差距为零时，鹰的爪子就够着兔子了。
#+end_quote

* 思考                                                            :思考:长期:
    什么是完美？怎么样才算是完美，完美主义的含义指的是什么。 *完美* 到底是什么，是完成，100%，不能
再改变，是大家对一个东西，一件事情的评价，或者是最高的评价。
    那么完美就是指的事情结束了，大家认可了，给出了非常高的评价。
    不愿意去做的原因从这里可以看出来两个
    1. 不确定性，做事情没有结果，或者没法达到一个终结状态，要一直去做，这个会
       引发 ~懒~ 这个选择，去做就会要一直做下去，还不知道什么时候才能结束。
    2. 别人的评价，这是评价体系的崩塌；只有别人认可才行。当你想去学习画画
       就开始担心自己画的不好那么就不会再想去画了，因为你再担心一个位置的评价
    3. 认知上的缺陷是什么？就是不知道一件事情该如何去做，脑子里天真的以为
       完成一件事情是静态的，做饭就是一下做好，宇宙的本质是动态的，不存在
       正确答案。说到这里和教育体系也有关系。很多事情都有一个标准答案，大家是为了
       向标准上面靠拢而行动；
    4. *标准答案* 从小到大就是标准答案，各种试卷各种标准；没有标准不行，但是标准不能只是
       唯一，只能是参考才行；对于语文，历史，政治等纯纯的就是在胡编乱造，上哪里去
       弄标准。还有好学生，好人，一个人就是用太多的标签去束缚了自我， *不敢去思考, 没有能力去思考* 
       中国的教育完全是只筛选不教育；人被太多的标签束缚了
       道德，法律，金钱，婚姻，亲情，爱情，孝顺，责任，义务，老实人、太过于可笑


    
* 权威                                                            :长期:
    最近看了不少 =大国工匠= 的嘲讽视频，宣传页确实离谱，手指感知5nm，um还有一些低级的错误
在20年前大家很喜欢看，很自豪；现在就是把大家当小丑，宣传口的人完全是向上管理，屁民
有什么用呢。
        到底谁有权力去评价你？你又该如何对待评价，如何采取评价给出的意见？
        中国现在到底是什么体制的国家呢？仔细看来就是一个苏系国家，但是发展，管理水平
    却不怎么好，未富先衰；经济腾飞也是全靠房地产，最后一地鸡毛，泡沫经济；不知道社会
    现在会如何发展。

       



