** orgmode使用latex
优秀的排版工具可以和org模式兼容预览,插入数学公式并且可以预览,还能支持
latex表格,非常好看; 使用的功能主要是latex preview,是一个内置的功能;

** 使用方法

*** method 1 preview-latex

    1. 系统安装latex支持,macOS可以安装 =mactex= ,这是为了可以编译latex语法;
    2. 展示,使用 ~dvipng~ 或者 ~dsvisvg~ 或者 ~image~ svg效果更好;
    3. 安装好之后调用预览函数即可,会把内容进行替换,svg是把png进一步变为svg进行展示;
    
***  使用prettify
这个原理是吧相应的字符进行替换,不是上面的生成png图片替换;
首先需要配置一下symbole-list映射关系,然后就会自动进行替换了
| 映射展示       | 效果 | 映射展示 | 效果  |
|--------------+-----+--------+------|
| lambda            | ->   | map    | /=    |
| !=            | ==   | <=      | >=    |
| ...            | \alpha   | \beta      | \gamma    |
| \epsilon            | \delta   | \zeta      | \lambda    |
| \rho            | \forall   | \Gamma      | \Delta    |
| \infty            | \times   | \tau      | \not |
| \times            | \div   | \longleftrightarrow      | \pm \mp  |
| \cup            | \langle   | \leftarrow \rightarrow    |      |
| \todo \done |     |        | \done  |

*16进制配置,需要去unicode码表值,以 #x开头* 例如 对号就是 =#x2705= 

$\not$ $\langle$ $\approx$  \rangle $\rangle$
$\prime$ $\wedge$   \Lambda  \Lambda \Pi \Phi \sigma \emptyset \Longleftarrow \Longrightarrow
\Leftarrow \subset \supset \leftarrow  $\Leftarrow$  \iff \implies 
\longleftrightarrow \Longleftrightarrow \longleftarrow \longrightarrow \leftarrow \rightarrow \Leftarrow \Rightarrow
$\leftarrow \rightarrow  \Leftarrow \Rightarrow \subset \supset$
$\leftarrow \rightarrow  \Leftarrow \Rightarrow \subset \supset$
$\longleftarrow \Leftarrow$
$\Leftrightarrow \leftrightarrow$
$\min \max$ $\mapsto$ $\ln$

*** $CDLatex$ 帮助输入数学公式
    [[https://orgmode.org/manual/CDLaTeX-mode.html][CDLatex参考文档]]
    - 按反引号可以帮助弹出latex输入语法,同时继续按可以进入到下一级别的符号;
    - *C-c {* 弹出环境模板页面,可以选择;
    - *TAB* 帮助编辑移动
    - 箭头技巧,在二级选项上面是长箭头,一级是短箭头
      *<或>* 是短箭头左右
      *[或]* 双箭头
      *-或=* 单双箭头左右方向
      #+begin_example
      \leftarrow \rightarrow \Leftarrow \Rightarrow \leftrightarrow \Leftrightarrow
      \longleftarrow \longrightarrow \Longleftarrow \Longrightarrow \longleftrightarrow \Longleftrightarrow
      #+end_example
\alpha 

\lambda  \lambda 
$\to$ 
  lambda
  \beta 
->  \pi 
\longrightarrow 
>= <= \alpha   
  $\xi$
\begin{equation}                        % arbitrary environments,
x=\sqrt{b}                              % even tables, figures, etc
\end{equation} 
\begin{equation}
\label{eq:1}
x=\sqrt{b}
\end{equation}

$dsfj$ 

$\alpha$

\begin{table}[htbp]
\caption[]{\label{tab:hahatable} }
\vspace{4mm}

\end{table}


$$E=E^3$$ 


\begin{array}{l} 
  a\mathop{{x}}\nolimits^{{2}}+bx+c=0 \\ 
  \Delta =\mathop{{b}}\nolimits^{{2}}-4ac \\ 
  \left\{\begin{matrix} 
  \Delta \gt 0\text{方程有两个不相等的实根} \\ 
  \Delta = 0\text{方程有两个相等的实根} \\ 
  \Delta \lt 0\text{方程无实根} 
\end{matrix}\right.    
\end{array} 


lambda
map -> 



\Pi 

\todo \done  :smile: 

\alpha 





\done 





** Latex语法
1. 行内公式
    *行内公式是在正文中嵌入的数学表达式，使用 $...$ 或 \(...\) 包围公式内容。*
    这是一个行内公式：$E=mc^2$。
    这是一个行内公式：\( E = mc^2 \)。

2. 独立公式
    *独立公式单独成行，使用 \[...\] 或 equation 环境。*

    示例（使用 \[...\]）
    这是一个独立公式：
	\[ E = mc^2 \]  
    示例（使用 equation 环境）：
	    \begin{equation}
	    E = mc^2
	    \end{equation}

3. 多行公式
    用于显示多行数学表达式的环境。
    常用环境有 align、gather 和 multline。

   1) align 环境：
       #+begin_src latex
	   \begin{align}
	   a & = b + c \\
	   d & = e + f
	   \end{align}


	   \begin{equation}
	   a & = b + c \\
	   d & = e + f
	   \end{equation}
       #+end_src
	   \begin{align}
	   a & = b + c \\
	   d & = e + f
	   \end{align}

	   \begin{equation}
	   a & = b + c \\
	   d & = e + f
	   \end{equation}
   2) gather 环境：
       #+begin_src latex
       \begin{gather}
       a = b + c \\
       d = e + f
       \end{gather}
       #+end_src
       \begin{gather}
       a = b + c \\
       d = e + f
       \end{gather}
   3) multline 环境：
       #+begin_src latex
       \begin{multline}
       a + b + c + d + e + f + g + h + i + j + k + l + m \\
       = n + o + p + q + r + s + t + u + v + w + x + y + z
       \end{multline}
       #+end_src
       \begin{multline}
       a + b + c + d + e + f + g + h + i + j + k + l + m \\
       = n + o + p + q + r + s + t + u + v + w + x + y + z
       \end{multline}

4. 分组公式
    用于显示一组相关公式的环境，如 alignat 和 cases。

   1) alignat 环境：
      #+begin_src latex
       \begin{alignat}{2}
       a & = b + c & \quad & \text{(公式1)} \\
       d & = e + f & \quad & \text{(公式2)}
       \end{alignat}
      #+end_src

       \begin{alignat}{2}
       a & = b + c & \quad & \text{(公式1)} \\
       d & = e + f & \quad & \text{(公式2)}
       \end{alignat}
   2) cases 环境：
       #+begin_src latex
	   \begin{equation}
	   f(x) = 
	   \begin{cases} 
	   x^2 & \text{if } x \geq 0 \\
	   -x^2 & \text{if } x < 0 
	   \end{cases}
	   \end{equation}
       #+end_src
       \begin{equation}
       f(x) = 
       \begin{cases} 
       x^2 & \text{if } x \geq 0 \\
       -x^2 & \text{if } x < 0 
       \end{cases}
       \end{equation}

5. 矩阵
    用于显示矩阵的环境，
    如 matrix、bmatrix、pmatrix、vmatrix 和 Vmatrix。

   1) matrix 环境：
       #+begin_src latex
       \begin{matrix}
       1 & 2 \\
       3 & 4
       \end{matrix}
       #+end_src
       \begin{matrix}
       1 & 2 \\
       3 & 4
       \end{matrix}
   2) bmatrix 环境（带方括号）：
      #+begin_src latex
       \begin{bmatrix}
       1 & 2 \\
       3 & 4
       \end{bmatrix}
      #+end_src
       \begin{bmatrix}
       1 & 2 \\
       3 & 4
       \end{bmatrix}
   3) pmatrix 环境（带圆括号）：
      #+begin_src latex
       \begin{pmatrix}
       1 & 2 \\
       3 & 4
       \end{pmatrix}
      #+end_src
       \begin{pmatrix}
       1 & 2 \\
       3 & 4
       \end{pmatrix}
   4) vmatrix 环境（带竖线）：
      #+begin_src latex
       \begin{vmatrix}
       1 & 2 \\
       3 & 4
       \end{vmatrix}
      #+end_src
       \begin{vmatrix}
       1 & 2 \\
       3 & 4
       \end{vmatrix}
   5) Vmatrix 环境（带双竖线）：
      #+begin_src latex
       \begin{Vmatrix}
       1 & 2 \\
       3 & 4
       \end{Vmatrix}
      #+end_src
       \begin{Vmatrix}
       1 & 2 \\
       3 & 4
       \end{Vmatrix}

6. 数学模式中的命令
    除了上述环境，LaTeX 还提供了许多命令来处理数学符号和格式。例如：
   1) 分数：\frac{a}{b}
       $\frac{a}{b}$
   2) 上标和下标：a^2 和 a_1
      $a^2, a_1$
   3) 根号：\sqrt{x}
      $\sqrt{x}$

7. 文字加粗
   可以使用 *mathbf* or *boldsymbol*

   1) =mathbf=
    #+begin_src latex
	\begin{document}

	这是一个行内公式：$\mathbf{E=mc^2}$。

	这是一个独立公式：
	\[
	\mathbf{E = mc^2}
	\]

	\end{document}


	这是一个行内公式：$\mathbf{E=mc^2}$。
    #+end_src
	    \begin{document}

	    这是一个行内公式：$\mathbf{E=mc^2}$。

	    这是一个独立公式：
	    \[
	    \mathbf{E = mc^2}
	    \]

	    \end{document}

    这是一个行内公式：$\mathbf{E=mc^2}$。
   2) =boldsymbol=
	#+begin_src latex
	  \begin{document}

	  这是一个行内公式：$\boldsymbol{\alpha + \beta = \gamma}$。

	  这是一个独立公式：
	  \[
	  \boldsymbol{\alpha + \beta = \gamma}
	  \]

	  \end{document}

	  这是一个行内公式：$\boldsymbol{\alpha + \beta = \gamma}$。
	  这是一个行内公式：$\boldsymbol{E = mc^2}$。
	  这是一个行内公式：$\mathbf{\alpha + \beta = \gamma}$。
	#+end_src
	\begin{document}

	这是一个行内公式：$\boldsymbol{\alpha + \beta = \gamma}$。

	这是一个独立公式：
	\[
	\boldsymbol{\alpha + \beta = \gamma}
	\]

	\end{document}
	这是一个行内公式：$\boldsymbol{\alpha + \beta = \gamma}$。
	这是一个行内公式：$\boldsymbol{E = mc^2}$。
	这是一个行内公式：$\mathbf{\alpha + \beta = \gamma}$。

	  \begin{document}

	  这是一个行内公式：$\boldsymbol{\alpha + \beta = \gamma}$。

	  这是一个独立公式：
	  \[
	  \boldsymbol{\alpha + \beta = \gamma}
	  \]

	  \[
	  \boldsymbol{\Delta + \beta = \gamma}
	  \]
	  \end{document}

8. 编写技巧
   - 公式换行 *\\*
这是一个带有换行的行内公式：$a = b + c \\ d = e + f$。

   - 
2. 添加空格
在 LaTeX 中，可以使用以下命令来添加空格：

\, ：表示一个很小的空格。
\: ：表示一个中等大小的空格。
\; ：表示一个大的空格。
\quad：表示一个四分之一的空格。
\enspace 
\qquad：表示一个二分之一的空格。
#+begin_latex
$a\!b$
$a\,b$
$a\:b$
$a\;b$
$a\enspace b$
$a\quad b$
===================
$a\!b$
$a\,b$
$a\:b$
$a\quad b$
$a\;b$
$a\enspace b$
$a\quad b$
$a\qquad b$
#+end_latex







